package com.youyuan.mybatis.dao;

import com.youyuan.mybatis.domain.Department;
import com.youyuan.mybatis.domain.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int deleteByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    Department selectByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    int updateByPrimaryKey(Department record);
}