package com.youyuan.mybatis.domain;

import java.io.Serializable;

public class Department implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.GUID
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    private Long guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.GUID
     *
     * @return the value of DEPARTMENT.GUID
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.GUID
     *
     * @param guid the value for DEPARTMENT.GUID
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @return the value of DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPARTMENT_NAME
     *
     * @param departmentName the value for DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbg.generated Tue Mar 20 18:51:30 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

	@Override
	public String toString() {
		return "Department [guid=" + guid + ", departmentName="
				+ departmentName + "]";
	}
}